defaults:
  - env: minigrid
  - learning: ippo-minigrid
  - ued: plr
  - _self_

"SEED": 2
"GROUP_NAME": "minigrid-ncc"
"ENTITY": "nathanmonette1"
"PROJECT": "minigrid"
"WANDB_MODE" : "disabled"
"SAVE_PATH": "checkpoints/new_minigrid"
"CHECKPOINT_SAVE_INTERVAL": 0
"META_LR": 0.01
"META_TRUNC": 1e-6
"META_OPTIMISTIC": False
"OPTIMISTIC": TRUE