"LR": 0.0014658280281033783
"WARMUP_UPDATES": 100
"NUM_ENVS": 256
"NUM_STEPS": 256
"EVAL_FREQ": 100
"TOTAL_TIMESTEPS": 3e8
"EVAL_TIMESTEPS": 2.5e7
"NUM_CHECKPOINTS": 4
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 1
"GAMMA": 0.995
"GAE_LAMBDA": 0.98
"CLIP_EPS": 0.2
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.001
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"FC_DIM_SIZE": 512
"HIDDEN_SIZE": 512
"ANNEAL_LR": True
"USE_LAYER_NORM": True
"LAMBDA_SCHEDULE": False